### ISSUE TITLE
Need more detailed error reporting

### ISSUE THREAD

**Issue by apkh** [apkh/ez#26]
It is not clear what's wrong from the message:

DEBUG [pool-2-thread-1](TitanServerAdapter.java:241) - toQueue for user=48, dest=/queue/errors
DEBUG [pool-2-thread-1](TitanServerAdapter.java:242) -   +--> payload=ru.ezdz.context.service.graph.exception.SchemaViolationException: Schema violation: LINK_TYPE
DEBUG [pool-2-thread-1](TitanServerAdapter.java:243) -   +--> origin=ru.ezdz.context.service.graph.ReplayMessage@72c32338[userId=48,operation=ERROR,projectId=<null>,payload=ru.ezdz.context.service.graph.exception.SchemaViolationException: Schema violation: LINK_TYPE,traceId=<null>]

**Comment by nickvl** [comment]
fixed.
some errors are still regular exceptions, but all existing code refactored
