### ISSUE TITLE
RexsterClient instance created constantly

### ISSUE THREAD

**Issue by apkh** [apkh/ez#3]
It is created for almost all transactions. Do we really need to recreate it?

 INFO [EZapp commands dispatcher](RexsterClientFactory.java:130) - Create RexsterClient instance: [hostname=192.168.11.128
port=8184
graph-name=graph
timeout-connection-ms=300
message-retry-count=2
timeout-write-ms=3000
timeout-read-ms=3000
max-async-write-queue-size=512000
message-retry-wait-ms=50
language=groovy
graph-obj-name=g
transaction=true
serializer=0]

**Comment by nickvl** [comment]
fixed in context branch
details: https://groups.google.com/forum/#!msg/aureliusgraphs/oPNrEb0MiN0/Ritc-OOEADkJ
