### ISSUE TITLE
rexster error

### ISSUE THREAD

**Issue by apkh** [apkh/ez#31]
rexster error: 

WARN [EZapp commands dispatcher](RexsterClient.java:217) - Rexster returned an error response for [r = g.v(sid); r.ifThenElse{it.type==P}{it.id}{it.as('x').inE.has('label',T.in,L).outV.loop('x'){it.object.type != P}{it.object.type == P}.path.transform{it.findAll{it instanceof Vertex}.id}.toList()[0].reverse()[0..<2]}] with params [{sid=88, P=PROJECT, L=[BASELINE, BOOK, TAG, VERSION, ARTICLE, REVIEW, COMMENT, PATCH]}]
DEBUG [pool-2-thread-1] (TitanServerAdapter.java:260) - toQueue for user=48, dest=/queue/errors
DEBUG [pool-2-thread-1] (TitanServerAdapter.java:261) -   +--> payload=ru.ezdz.context.service.graph.exception.TitanException: com.tinkerpop.rexster.client.RexProException: An error occurred while processing the script for language [groovy]. All transactions across all graphs in the session have been concluded with failure: javax.script.ScriptException: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke method ifThenElse() on null object
DEBUG [pool-2-thread-1](TitanServerAdapter.java:262) -   +--> origin=ru.ezdz.context.service.graph.ReplayMessage@7f940a37[userId=48,operation=ERROR,projectId=<null>,payload=ru.ezdz.context.service.graph.exception.TitanException: com.tinkerpop.rexster.client.RexProException: An error occurred while processing the script for language [groovy]. All transactions across all graphs in the session have been concluded with failure: javax.script.ScriptException: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke method ifThenElse() on null object,traceId=<null>]

it was done after:

 INFO [EZapp commands dispatcher](LogStrategy.java:184) - calling: readNodeRelationship(3 arguments: userId=48, sid=88, labels=ArrayList[{ARTICLE}])
DEBUG [EZapp commands dispatcher](LogStrategy.java:219) - calling: readNodeRelationship(3 arguments: userId=48, sid=88, labels=ArrayList[{ARTICLE}])

**Comment by nickvl** [comment]
probably is not valid anymore. I think it could be closed.
